# quartz??
org.quartz.scheduler.instanceName = shivaScheduler
org.quartz.scheduler.instanceId = AUTO
org.quartz.scheduler.rmi.export = false
org.quartz.scheduler.rmi.proxy = false
org.quartz.scheduler.wrapJobExecutionInUserTransaction = false

# ?????
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 20
org.quartz.threadPool.threadPriority = 5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread = true

# JobStore??
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
# ?????
org.quartz.jobStore.dataSource = myDS
# ?????
org.quartz.jobStore.tablePrefix = QRTZ_
org.quartz.jobStore.useProperties = false

# ????
org.quartz.jobStore.isClustered = true
# ?????????????????
org.quartz.jobStore.clusterCheckinInterval = 15000
# ????????????
org.quartz.jobStore.misfireThreshold = 60000
org.quartz.jobStore.maxMisfiresToHandleAtATime = 1
org.quartz.jobStore.txIsolationLevelSerializable = true

# ?????
org.quartz.dataSource.myDS.driver = com.mysql.cj.jdbc.Driver
org.quartz.dataSource.myDS.URL = jdbc:mysql://81.69.250.183:3306/pufferfishscheduler?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
org.quartz.dataSource.myDS.user = root
org.quartz.dataSource.myDS.password = Etl2025
org.quartz.dataSource.myDS.maxConnections = 10
# Mysql????
org.quartz.dataSource.myDS.validationQuery = SELECT 1

